services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongodata:
